on: [push]
name: Test action
jobs:
  install_paper:
    runs-on: ubuntu-latest
    name: Download PaperMC
    steps:
      - name: Download using own action
        uses: just-dev-creator/install-paper@master
        with:
          path: './paper.jar'
      - name: Check if file exists
        run: file paper.jar